### ISSUE TITLE
Where‘s the critical path related algrithm in the 2022 paper?

### ISSUE THREAD

**Issue by ActivePeter** [lzjzx1122/FaaSFlow#1]
I'm recently doing some work about serverless, and I want to reimplemented the FaaSFlow‘s main algrithm(scheduler and scaler).
I'm not clear about the detail of implementation, so I come here to ask for help.

**Comment by lzjzx1122** [comment]
Yeah, you found the point. In FaaSFlow v2.0 we want to add a kind of real-time dataflow-based scheduling to specify the host address(related to src/workflow_manager/gateway.py), and it is ongoing research. Therefore the grouping algorithm from v1.0 is no longer needed and also not updated into FaaSFlow v2.0. If you want to re-implemented the FaaSFlow‘s grouping algorithm, I think you can check v1.1 ([Link here](https://github.com/lzjzx1122/FaaSFlow/tree/64a95479af142f34aa45f832a29beced086a13ea)) and find it in src/grouping/grouping.py.

Hope your research is progressing well and welcome to ask for help.
